/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        "on-surface-variant": "#404945",
        "surface-tint": "#376757",
        "on-background": "#121e18",
        "outline-variant": "#c0c9c3",
        "on-secondary-container": "#316e52",
        "primary-fixed-dim": "#9ed1bd",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#e6f4ea",
        "tertiary-container": "#004f35",
        "on-primary-fixed-variant": "#1d4f40",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#121e18",
        "inverse-surface": "#27332c",
        "inverse-primary": "#9ed1bd",
        "secondary-fixed": "#b1f0ce",
        "on-secondary": "#ffffff",
        "outline": "#707974",
        "primary-fixed": "#baeed9",
        "primary": "#003629",
        "secondary": "#2c694e",
        "surface-container-high": "#ddece1",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1b4d3e",
        "surface-container-highest": "#d8e6dc",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#6ffbbe",
        "tertiary": "#003623",
        "surface-variant": "#d8e6dc",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#95d4b3",
        "tertiary-fixed-dim": "#4edea3",
        "surface": "#effdf2",
        "on-tertiary-container": "#32c98f",
        "on-secondary-fixed-variant": "#0e5138",
        "background": "#effdf2",
        "surface-container-low": "#e9f7ed",
        "on-tertiary-fixed-variant": "#005236",
        "surface-dim": "#cfded3",
        "surface-container": "#e3f1e7",
        "on-tertiary-fixed": "#002113",
        "secondary-container": "#aeeecb",
        "on-primary-fixed": "#002117",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#002114",
        "surface-bright": "#effdf2",
        "on-primary-container": "#8abda9"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "20px",
        unit: "4px",
        lg: "24px",
        xl: "32px",
        "3xl": "64px",
        md: "16px",
        "2xl": "48px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
